theme: jekyll-theme-slate
title: Haanvid Lee
description: Electrical Engineering MS Student (Degree expected at Feb. 2017)
description: Cognitive Neuro-Robotics Lab
description: Korea Advanced Institute of Science and Technology (KAIST)
description: Daejeon, Republic of Korea
author_email: haanvidlee@gmail.com
