theme: jekyll-theme-slate
title: Haanvid Lee
description: Electrical Engineering MS Student (Degree expected at Feb. 2017)..Cognitive Neuro-Robotics Lab Korea Advanced Institute of Science and Technology (KAIST) Daejeon, Republic of Korea
