theme: jekyll-theme-slate
title: Haanvid Lee
description: | Electrical Engineering MS Student (Degree expected at Feb. 2017)\n Cognitive Neuro-Robotics Lab\n Korea Advanced Institute of Science and Technology (KAIST)\n Daejeon, Republic of Korea
author_email: haanvidlee@gmail.com
